title: Blog of Janibek
email: janibek.marshal@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Android developer from land of steppe.
  Working at kolesa as Android team lead.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://janibek.marshal.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: megasuperhero
github_username:  JohnMars

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-110082079-2
