title: Blog of Janibek
email: janibek.marshal@gmail.com
description: >-
  Android developer from land of steppe.
  Working at kolesa as Android team lead.
# Url configuration
baseurl: ""
url: "http://janibek.marshal.com"
# Social networks
twitter_username: megasuperhero
github_username:  JohnMars
instagram_username: john_marshal
# Commenting
disqus:
  shortname: janibek-marshal

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-110082079-2
